Add a concepts/intercepts page with Brian's animation
telepresenceio/telepresence.io pull request #62
Opened 2021-08-30 00:25 UTC by LukeShu

Signed-off-by: Luke Shumaker <lukeshu@datawire.io>

2021-08-30 17:07 UTC, LukeShu commented
v2: I've changed which browser extension we link to to set the headers

2021-08-30 21:31 UTC, donnyyung commented on docs/pre-release/concepts/intercepts.md
> +    telepresence intercept SERVICENAME --http-match=Personal-Intercept=126a72c7-be8b-4329-af64-768e207a184b
I would add a qualifier here saying "we're using `Personal-Intercept=126a72c7-be8b-4329-af64-768e207a184b` as the header, but you can use any <key>=<value> that you want" or something like that just so it's abundantly obvious that this value can, and should, change.

2021-08-30 21:44 UTC, donnyyung requested changes
This looks good just one suggestion to make it clear that the header you picked is just an example, since I could see people copying that command verbatim and thinking they need to use that specific http-header whenever they do a personal intercept.

2021-08-31 15:37 UTC, donnyyung approved these changes
LGTM thanks!

2021-09-01 02:01 UTC, LukeShu commented
I clicked merge several hours ago.  I swear I did.  Why isn't it merged!?

2021-09-01 02:01 UTC, merged